import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
  AiFillGithub,
  AiFillLinkedin,
  AiOutlineMail,
  AiFillYoutube,
} from 'react-icons/ai';
import { useState } from 'react';

import Image from 'next/legacy/image';
import AnnProfilePhoto from '../public/AnnBuiProfilePhoto.png';
import Developing from '../public/Developing.png';
import UXUI from '../public/UX:UI.png';
import Consulting from '../public/Consulting.png';
import Testing from '../public/Testing.png';
import Logo from '../public/Logo2.png';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=0.7" />
        <title>Ann Bui Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-700">
        <section className="min-h-fit">
          {/* -------NAV BAR SECTION------- */}
          <nav className="sticky top-0 z-30 w-full px-2 py-5 bg-white sm:px-4 flex justify-between">
            <Image
              className="text-xl"
              src={Logo}
              width={100}
              height={100}
              alt="Developing Serive An Bui Provides"
            />

            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-sm"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-blue-500 to-blue-200 text-white px-4 py-2 rounded-md ml-8 font-Montserrat"
                  href="https://resume.creddle.io/resume/j1ryfjyu3f1"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/* -------ABOUT ME/ FRONT PAGE SECTION------- */}
          <div className="xl:flex row md:w-full">
            <div>
              <div className="text-center m-auto md:text-left">
                <h2 className="text-5xl py-2 text-blue-600 font-medium md:text-7xl">
                  Heyyy, I am Ann Bui
                </h2>
                <h3 className="text-2xl py-2 md:text-3xl">
                  Jr Front-end Dev & UXUI Designer
                </h3>
                <p className="text-md lg:pr-14 py-5 leading-6 text-gray-800 md:text-xl max-w-4xl mx-auto">
                  I have a strong interest in Web Development and love the
                  ability to be creative and design visually appealing
                  applications.
                  <br />
                  Passionate about creating beautiful and user-centered products
                  that bring joy and meet the needs of users in their daily
                  lives.
                  <br />
                  <br />
                  High achiever, detail oriented to pixel perfect with
                  experience in Project Management and Documentation. With a
                  “work hard play hard” attitude, a willingness to learn, and a
                  desire to get my job done excellently!
                  <br />
                  <br />
                  Though I still have a lot to learn, I am eager to do so and
                  look forward to sharpening the skills I have gained from my
                  education.
                </p>
              </div>
              {/* -------SOCIAL MEDIA ICONS SECTION------- */}
              <div className=" text-4xl flex justify-center gap-14 py-3 text-gray-600 md:justify-start md:gap-6 md:mb-10 ">
                <a
                  href="https://github.com/thaian161"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <AiFillGithub className="hover:text-blue-700 hover:scale-125" />
                </a>
                <a
                  href="https://www.linkedin.com/in/thaian161/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <AiFillLinkedin className="hover:text-blue-700 hover:scale-125" />
                </a>
                <a href="mailto:hello.annbui@gmail.com">
                  <AiOutlineMail className="hover:text-blue-700 hover:scale-125" />
                </a>
                <a
                  href="https://www.youtube.com/@JanthBui/videos"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <AiFillYoutube className="hover:text-blue-700 hover:scale-125" />
                </a>
              </div>
            </div>

            <div>
              {/* -------MY PROFILE PHOTO SECTION------- */}

              <div
                className="relative rounded-xl mx-auto mb-20 bg-gradient-to-b from-blue-500 w-80 h-80 mt-10 overflow-hidden md:h-94 md:w-94 md:mt-10 lg:mt-40 md:my-4 md:mb-20"
                style={{
                  boxShadow: '30px 30px white, 30px 30px 0 6px blue',
                }}
              >
                <Image
                  src={AnnProfilePhoto}
                  layout="fill"
                  objectFit="cover"
                  alt="Ann Bui Profile Picture"
                />
              </div>
            </div>
          </div>
        </section>

        {/* ------- SERVICES I OFFER SECTION------ */}
        <section>
          <div>
            <h3 className="text-3xl py-1"> Service I Offer</h3>
            <p className="text-md py-5 leading-6 text-gray-800">
              Aside from my full-time job, I am also{' '}
              <span className="text-blue-500">
                available for part-time freelance work
              </span>
              . Below are the services I offer.
            </p>
          </div>
          {/* -------THREE SERVICES SECTION------- */}
          <div className="lg:flex gap-10">
            {/* -------DEVELOPING WEB CARD-------*/}
            <div className="text-center shadow-lg p-10 rounded-xl my-10 ">
              <Image
                src={Developing}
                width={100}
                height={100}
                alt="Developing Serive An Bui Provides"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Developing Website || Web App
              </h3>
              <li className="text-left">
                Build static website, landing page, blogs...etc
              </li>
              <li className="text-left">Build web applications</li>
              <li className="text-left">
                Develop WordPress templates, pages, and posts, document the
                process, and make user guide for future reference
              </li>
              <h4 className="py-4 text-blue-600">
                Technology:
                <span className="text-gray-800"> React, Wordpress</span>
              </h4>
            </div>

            {/* -------UXUI CARD-------*/}
            <div className="text-center shadow-lg p-10 rounded-xl my-10 ">
              <Image
                src={UXUI}
                width={100}
                height={100}
                alt="UXUI Design Serive An Bui Provides"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">UX/UI Design</h3>
              <li className="text-left">
                UX research: understand user-story, conduct user research and
                analyst data collected from surveys
              </li>
              <li className="text-left">
                Create user interface by choosing color scheme, typography,
                design pattern and system
              </li>
              <li className="text-left">
                Build wire-frame, prototype and final look mock-up
              </li>
              <h4 className="py-4 text-blue-600">
                Technology:
                <span className="text-gray-800"> Figma, Adobe Express </span>
              </h4>
            </div>

            {/* -------CONSULTING CARD-------*/}
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-300">
              <Image
                src={Consulting}
                width={100}
                height={100}
                alt="Consulting Serive An Bui Provides"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">Consulting</h3>
              <li className="text-left">
                You want to know whether your product is user-friendly or need
                feedback on the UX/UI? Contact me :D
              </li>
              <li className="text-left">
                Website audit to improve SEO, or re-design your entire
                website/app interface
              </li>
              <li className="text-left">
                Feeling nervous before your interview? I can conduct a mock
                interview and provide feedback
              </li>
              <h4 className="py-4 text-blue-600">
                Contact me via:
                <span className="text-gray-800"> email or linkedin </span>
              </h4>
            </div>
          </div>
        </section>
        {/* -------PROJECTS PORTFOLIO SECTION------- */}
        <section>
          <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-5 leading-6 text-gray-800">
              Here are some of my{' '}
              <span className="text-blue-500">coding projects</span> and{' '}
              <span className="text-blue-500">UX/UI design</span> I have done so
              far
            </p>
          </div>
          {/* -------SHOWCASE EACH PROJECT SECTION------- */}
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            {/* ---------------------Dirty Paws-------------------------- */}
            <div className="basis-1/3 flex-1">
              <Image
                src={Testing}
                className="rounded-lg object-cover hover:scale-110"
                width={'100%'}
                height={'50%'}
                layout="responsive"
                alt="Dirty Paws Project"
              />
              <div className="flex items-center justify-center">
                <button className=" text-lg w-1/2 px-6 py-3 m-4 duration-200 hover:scale-125 hover:text-blue-700">
                  <a
                    href="https://www.youtube.com/watch?v=vDzoe_sz0AQ"
                    rel="noreferrer"
                    target="_blank"
                  >
                    Demo
                  </a>
                </button>
                <button className=" text-lg w-1/2 px-6 py-3 m-4 duration-200 hover:scale-125 hover:text-blue-700">
                  <a
                    href="https://github.com/thaian161/Dirty-Paws"
                    rel="noreferrer"
                    target="_blank"
                  >
                    Code
                  </a>
                </button>
              </div>
            </div>
            {/* ---------------------Expense App-------------------------- */}
            <div className="basis-1/3 flex-1">
              <Image
                src={Testing}
                className="rounded-lg object-cover hover:scale-110"
                width={'100%'}
                height={'50%'}
                layout="responsive"
                alt="Expense App Project"
              />
              <div className="flex items-center justify-center">
                <button className=" text-lg w-1/2 px-6 py-3 m-4 duration-200 hover:scale-125 hover:text-blue-700">
                  <a
                    href="https://www.youtube.com/watch?v=vDzoe_sz0AQ"
                    rel="noreferrer"
                    target="_blank"
                  >
                    Demo
                  </a>
                </button>
                <button className=" text-lg w-1/2 px-6 py-3 m-4 duration-200 hover:scale-125 hover:text-blue-700">
                  <a
                    href="https://github.com/thaian161/Dirty-Paws"
                    rel="noreferrer"
                    target="_blank"
                  >
                    Code
                  </a>
                </button>
              </div>
            </div>
            {/* ------------------------Jugnle Plant Shop----------------------- */}
            <div className="basis-1/3 flex-1">
              <Image
                src={Testing}
                className="rounded-lg object-cover hover:scale-110"
                width={'100%'}
                height={'50%'}
                layout="responsive"
                alt="Jungle Plan Shop Project"
              />
              <div className="flex items-center justify-center">
                <button className=" text-lg w-1/2 px-6 py-3 m-4 duration-200 hover:scale-125 hover:text-blue-700">
                  <a
                    href="https://www.youtube.com/watch?v=vDzoe_sz0AQ"
                    rel="noreferrer"
                    target="_blank"
                  >
                    Demo
                  </a>
                </button>
                <button className=" text-lg w-1/2 px-6 py-3 m-4 duration-200 hover:scale-125 hover:text-blue-700">
                  <a
                    href="https://github.com/thaian161/Dirty-Paws"
                    rel="noreferrer"
                    target="_blank"
                  >
                    Code
                  </a>
                </button>
              </div>
            </div>
            {/* ------------------Bake It Up----------------------------- */}

            <div className="basis-1/3 flex-1">
              <Image
                src={Testing}
                className="rounded-lg object-cover hover:scale-110"
                width={'100%'}
                height={'50%'}
                layout="responsive"
                alt="Bake It Up"
              />
              <div className="flex items-center justify-center">
                <button className=" text-lg w-1/2 px-6 py-3 m-4 duration-200 hover:scale-125 hover:text-blue-700">
                  <a
                    href="https://www.youtube.com/watch?v=vDzoe_sz0AQ"
                    rel="noreferrer"
                    target="_blank"
                  >
                    Demo
                  </a>
                </button>
                <button className=" text-lg w-1/2 px-6 py-3 m-4 duration-200 hover:scale-125 hover:text-blue-700">
                  <a
                    href="https://github.com/thaian161/Dirty-Paws"
                    rel="noreferrer"
                    target="_blank"
                  >
                    Code
                  </a>
                </button>
              </div>
            </div>
            {/* --------------------Tweeter--------------------------- */}

            <div className="basis-1/3 flex-1">
              <Image
                src={Testing}
                className="rounded-lg object-cover hover:scale-110"
                width={'100%'}
                height={'50%'}
                layout="responsive"
                alt="Tweeter Project"
              />
              <div className="flex items-center justify-center">
                <button className=" text-lg w-1/2 px-6 py-3 m-4 duration-200 hover:scale-125 hover:text-blue-700">
                  <a
                    href="https://www.youtube.com/watch?v=vDzoe_sz0AQ"
                    rel="noreferrer"
                    target="_blank"
                  >
                    Demo
                  </a>
                </button>
                <button className=" text-lg w-1/2 px-6 py-3 m-4 duration-200 hover:scale-125 hover:text-blue-700">
                  <a
                    href="https://github.com/thaian161/Dirty-Paws"
                    rel="noreferrer"
                    target="_blank"
                  >
                    Code
                  </a>
                </button>
              </div>
            </div>
            {/* -----------------------NFlyte Figma Mock-up------------------------ */}

            <div className="basis-1/3 flex-1">
              <Image
                src={Testing}
                className="rounded-lg object-cover hover:scale-110"
                width={'100%'}
                height={'50%'}
                layout="responsive"
                alt="Nflyte Mock-up Project"
              />
              <div className="flex items-center justify-center">
                <button className=" text-lg w-1/2 px-6 py-3 m-4 duration-200 hover:scale-125 hover:text-blue-700">
                  <a
                    href="https://www.youtube.com/watch?v=vDzoe_sz0AQ"
                    rel="noreferrer"
                    target="_blank"
                  >
                    Demo
                  </a>
                </button>
                <button className=" text-lg w-1/2 px-6 py-3 m-4 duration-200 hover:scale-125 hover:text-blue-700">
                  <a
                    href="https://github.com/thaian161/Dirty-Paws"
                    rel="noreferrer"
                    target="_blank"
                  >
                    Code
                  </a>
                </button>
              </div>
            </div>
            {/* ----------------------------------------------- */}
          </div>
        </section>
      </main>

      <footer>
        <div className="text-center mt-2">
          Made with lots of -❤️- by Ann Bui
        </div>
        <div className="text-2xl flex justify-center gap-4 py-3 mb-2 text-gray-600">
          <a
            href="https://github.com/thaian161"
            target="_blank"
            rel="noopener noreferrer"
          >
            <AiFillGithub className="hover:text-blue-700 hover:scale-125" />
          </a>
          <a
            href="https://www.linkedin.com/in/thaian161/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <AiFillLinkedin className="hover:text-blue-700 hover:scale-125" />
          </a>
          <a href="mailto:hello.annbui@gmail.com">
            <AiOutlineMail className="hover:text-blue-700 hover:scale-125" />
          </a>
          <a
            href="https://www.youtube.com/@JanthBui/videos"
            target="_blank"
            rel="noopener noreferrer"
          >
            <AiFillYoutube className="hover:text-blue-700 hover:scale-125" />
          </a>
        </div>
      </footer>
    </div>
  );
}
